export default {
  end: {
    winning: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/MusicEx/MusicEx_Win.mp3',
    failing: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/MusicEx/MusicEx_Lose.mp3'
  },
  welcome: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/MusicEx/MusicEx_Welcome.mp3',
  welcome: 'https://static.pushy.site/game/music/game-center-bgm.mp3',
  card: {
    SINGLE: {
      ONE: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_1.mp3',
      TWO: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_2.mp3',
      THREE: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_3.mp3',
      FOUR: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_4.mp3',
      FIVE: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_5.mp3',
      SIX: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_6.mp3',
      SEVEN: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_7.mp3',
      EIGHT: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_8.mp3',
      NINE: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_9.mp3',
      TEN: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_10.mp3',
      JACK: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_11.mp3',
      LADY: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_12.mp3',
      KING: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_13.mp3',
      SMALL_JOKER: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_14.mp3',
      BIG_JOKER: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_15.mp3'
    },
    PAIR: {
      ONE: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_dui1.mp3',
      TWO: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_dui2.mp3',
      THREE: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_dui3.mp3',
      FOUR: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_dui4.mp3',
      FIVE: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_dui5.mp3',
      SIX: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_dui6.mp3',
      SEVEN: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_dui7.mp3',
      EIGHT: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_dui8.mp3',
      NINE: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_dui9.mp3',
      TEN: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_dui10.mp3',
      JACK: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_dui11.mp3',
      LADY: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_dui12.mp3',
      KING: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_dui13.mp3'
    },
    THREE: '',
    THREE_WITH_ONE: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_sandaiyi.mp3',
    THREE_WITH_PAIR: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_sandaiyidui.mp3',
    BOMB: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_zhadan.mp3',
    JOKER_BOMB: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_wangzha.mp3',
    STRAIGHT: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_shunzi.mp3',
    STRAIGHT_PAIR: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_liandui.mp3',
    AIRCRAFT: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_feiji.mp3',
    AIRCRAFT_WITH_WINGS: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_feiji.mp3',
    FOUR_WITH_TWO: 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_sidaier.mp3'
  },
  chat: {
    '1': 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_Chat_1.mp3',
    '2': 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_Chat_2.mp3',
    '3': 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_Chat_3.mp3',
    '4': 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_Chat_4.mp3',
    '5': 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_Chat_5.mp3',
    '6': 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_Chat_6.mp3',
    '7': 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_Chat_7.mp3',
    '8': 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_Chat_8.mp3',
    '9': 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_Chat_9.mp3',
    '10': 'https://hlddz.huanle.qq.com/resRoot-1.3.0.3/Sound/Man/Man_Chat_10.mp3',
    '11': 'static/audio/102840711-1-208 00_01_27.90-00_01_30.90.mp3',
    '12': 'static/audio/lbw_boom.mp3',
  }
}
